#!/usr/bin/expect

# Automated check if SMTP SendGrid credentials are correct through telnet
#
# Example use:
# ./test_sendgrid_credentials.exp username password em_domain
# ./test_sendgrid_credentials.exp viktor viktor123 em.viktor.com
#
# Dependencies: expect, telnet, base64
# Author: Viktor Nonov

set timeout 30
set username [lindex $argv 0]
set password [lindex $argv 1]
set email_server [lindex $argv 2]
set encoded_username [exec echo -n $username | base64]
set encoded_password [exec echo -n $password | base64]


puts "gonna connect to smtp.sendgrid.net with following data:"
puts "username: $username"
puts "password: $password"
puts "email server: $email_server"

spawn telnet smtp.sendgrid.net 587
expect "220 SG ESMTP service ready at"
send "ehlo $email_server\r"
expect "250 AUTH=PLAIN LOGIN"
send "auth login\r"
expect "334 "
send "$encoded_username\r"
expect "334 UGFzc3dvcmQ6"
send "$encoded_password\r"
expect "235"
send "QUIT\r"
expect eof
